import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./components/StoreProvider";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inventory System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <CookiesProvider>
        <html lang="en" data-theme="corporate">
          <body className={inter.className}>{children}</body>
        </html>
      </CookiesProvider>
    </StoreProvider>
  );
}
